sudo: false

language: node_js
node_js:
  - 10
  - 13
env:
  - CI=true
  - CI_BUILD=true
  - CI_STORYBOOK=true
script:
  -  if [ "${CI}" = "true" ]; then yarn test -- --coverage; fi
  -  if [ "${CI_BUILD}" = "true" ]; then yarn build; fi
  -  if [ "${CI_STORYBOOK}" = "true" ]; then yarn build-storybook; fi
